# Generated by Django 4.2.16 on 2025-02-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("group_type", models.CharField(max_length=100)),
                ("group_size", models.IntegerField()),
                ("contactname", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=10)),
                ("date_of_visit", models.DateField()),
                ("time_of_visit", models.TimeField()),
                ("place_of_visit", models.CharField(max_length=100)),
                ("tour_package", models.CharField(max_length=100)),
                ("payment_method", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Otp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(blank=True, max_length=10, null=True)),
                ("otp", models.CharField(max_length=6)),
                ("is_verified", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SoloBooking",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("contact_name", models.CharField(max_length=255)),
                ("s_email", models.EmailField(max_length=254)),
                ("s_phone", models.CharField(max_length=10)),
                ("s_date_of_visit", models.DateField()),
                ("s_time_of_visit", models.TimeField()),
                ("s_place_of_visit", models.CharField(max_length=100)),
                ("s_tour_package", models.CharField(max_length=100)),
                ("s_payment_method", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="TourismSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("categories", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="tourism_sites/")),
            ],
        ),
    ]
