# Generated by Django 4.2.16 on 2025-02-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tour", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="status",
            field=models.TextField(default="Pending", max_length=100),
        ),
        migrations.AddField(
            model_name="solobooking",
            name="s_status",
            field=models.TextField(default="Pending", max_length=100),
        ),
    ]
