# Generated by Django 4.2.16 on 2025-02-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tour", "0002_booking_status_solobooking_s_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="solobooking",
            name="s_status",
            field=models.BooleanField(default=False),
        ),
    ]
