# Generated by Django 4.2.16 on 2025-02-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tour", "0002_solobooking_tourismsite"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_type", models.CharField(max_length=100)),
                ("group_size", models.IntegerField()),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=10)),
                ("date_of_visit", models.DateField()),
                ("time_of_visit", models.TimeField()),
                ("place_of_visit", models.CharField(max_length=100)),
                ("tour_package", models.CharField(max_length=100)),
                ("payment_method", models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(name="SoloBooking",),
    ]
