# Generated by Django 4.2.16 on 2025-02-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tour", "0003_booking_delete_solobooking"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="contactname",
            field=models.CharField(default="Unknown", max_length=255),
        ),
    ]
