# Generated by Django 4.2.16 on 2025-03-05 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tour", "0003_alter_booking_status_alter_solobooking_s_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tourismsite", old_name="categories", new_name="place",
        ),
        migrations.RemoveField(model_name="tourismsite", name="price",),
        migrations.AddField(
            model_name="tourismsite",
            name="description",
            field=models.TextField(default="No description available"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.TextField(default="Pending", max_length=100),
        ),
        migrations.AlterField(
            model_name="solobooking",
            name="s_status",
            field=models.TextField(default="Pending", max_length=100),
        ),
        migrations.CreateModel(
            name="Itinerary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_number", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "meals",
                    models.CharField(
                        help_text="E.g., B, L & D for Breakfast, Lunch & Dinner",
                        max_length=50,
                    ),
                ),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itinerary",
                        to="tour.tourismsite",
                    ),
                ),
            ],
            options={"ordering": ["day_number"],},
        ),
    ]
