# Generated by Django 4.2.16 on 2025-03-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tour", "0004_rename_categories_tourismsite_place_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tourismsite",
            name="image",
            field=models.ImageField(upload_to=""),
        ),
    ]
