# Generated by Django 4.2.16 on 2025-02-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tour", "0004_booking_contactname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="contactname",
            field=models.CharField(max_length=255),
        ),
    ]
