# Generated by Django 4.2.16 on 2025-02-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tour", "0005_alter_booking_contactname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="group_size",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="booking",
            name="group_type",
            field=models.CharField(
                choices=[("Solo", "Solo"), ("Group", "Group")],
                default="Solo",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="name",
            field=models.CharField(default="Solo", max_length=100),
        ),
    ]
