# Generated by Django 4.2.16 on 2025-03-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tour", "0005_alter_tourismsite_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="TanzaniaSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(default="No description available")),
                ("place", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="")),
            ],
        ),
        migrations.AddField(
            model_name="tourismsite",
            name="details",
            field=models.TextField(default="No details available"),
        ),
    ]
