# Generated by Django 4.2.16 on 2025-03-06 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tour", "0006_tanzaniasite_tourismsite_details"),
    ]

    operations = [
        migrations.RemoveField(model_name="booking", name="group_size",),
        migrations.RemoveField(model_name="booking", name="group_type",),
        migrations.RemoveField(model_name="booking", name="payment_method",),
    ]
