# Generated by Django 4.2.16 on 2025-02-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tour", "0006_alter_booking_group_size_alter_booking_group_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking", name="group_size", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="booking",
            name="group_type",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="booking", name="name", field=models.CharField(max_length=100),
        ),
    ]
