# Generated by Django 4.2.16 on 2025-03-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tour", "0007_remove_booking_group_size_remove_booking_group_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itinerary",
            name="meals",
            field=models.TextField(
                help_text="E.g., B, L & D for Breakfast, Lunch & Dinner"
            ),
        ),
    ]
