# Generated by Django 4.2.16 on 2025-02-23 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tour", "0007_alter_booking_group_size_alter_booking_group_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SoloBookingForm",
            fields=[
                (
                    "booking_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="tour.booking",
                    ),
                ),
                ("contact_name", models.CharField(max_length=255)),
                ("s_email", models.EmailField(max_length=254)),
                ("s_phone", models.CharField(max_length=10)),
                ("s_date_of_visit", models.DateField()),
                ("s_time_of_visit", models.TimeField()),
                ("s_place_of_visit", models.CharField(max_length=100)),
                ("s_tour_package", models.CharField(max_length=100)),
                ("s_payment_method", models.CharField(max_length=100)),
            ],
            bases=("tour.booking",),
        ),
    ]
