# Generated by Django 4.2.16 on 2025-02-23 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tour", "0008_solobookingform"),
    ]

    operations = [
        migrations.RenameModel(old_name="SoloBookingForm", new_name="SoloBooking",),
    ]
