# Generated by Django 4.2.16 on 2025-03-06 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tour", "0009_contactmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tanzania_Itinerary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_number", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "meals",
                    models.TextField(
                        help_text="E.g., B, L & D for Breakfast, Lunch & Dinner"
                    ),
                ),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itinerary",
                        to="tour.tanzaniasite",
                    ),
                ),
            ],
        ),
    ]
