# Generated by Django 4.2.16 on 2025-03-06 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tour", "0011_tanzaniasite_details_alter_tanzania_itinerary_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tanzania_itinerary", options={"ordering": ["day_number"]},
        ),
    ]
