# Generated by Django 4.2.16 on 2025-03-09 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tour", "0012_alter_tanzania_itinerary_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="UgandaSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(default="No description available")),
                ("place", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="")),
                ("details", models.TextField(default="No details available")),
            ],
        ),
        migrations.AlterModelOptions(name="itinerary", options={"ordering": ["name"]},),
        migrations.AlterModelOptions(
            name="tanzania_itinerary", options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="Uganda_Itinerary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_number", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "meals",
                    models.TextField(
                        help_text="E.g., B, L & D for Breakfast, Lunch & Dinner"
                    ),
                ),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Ug_itinerary",
                        to="tour.ugandasite",
                    ),
                ),
            ],
            options={"ordering": ["name"],},
        ),
    ]
