# Generated by Django 5.0.6 on 2025-03-16 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0013_ugandasite_alter_itinerary_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='tour_package',
        ),
        migrations.RemoveField(
            model_name='solobooking',
            name='s_tour_package',
        ),
    ]
