# Generated by Django 5.0.6 on 2025-04-04 14:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tour", "0014_remove_booking_tour_package_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="end_of_visit",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
