# Generated by Django 5.0.6 on 2025-04-04 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tour", "0016_alter_booking_end_of_visit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="end_of_visit",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 4, 11, 14, 54, 23, 36709, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
