# Generated by Django 5.0.6 on 2025-04-04 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tour", "0017_alter_booking_end_of_visit"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="tour_package",
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name="booking",
            name="end_of_visit",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 4, 11, 15, 16, 50, 557752, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
