# Generated by Django 5.0.6 on 2025-04-04 15:51

import tour.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tour", "0018_booking_tour_package_alter_booking_end_of_visit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="end_of_visit",
            field=models.DateTimeField(default=tour.models.get_end_of_visit),
        ),
    ]
