# Generated by Django 5.0.6 on 2025-04-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tour", "0019_alter_booking_end_of_visit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking", name="end_of_visit", field=models.DateTimeField(),
        ),
    ]
