# Generated by Django 5.0.6 on 2025-04-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tour", "0020_alter_booking_end_of_visit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="tour_package",
            field=models.CharField(default="Basic Package", max_length=100),
        ),
    ]
