# Generated by Django 5.0.6 on 2025-04-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tour", "0021_alter_booking_tour_package"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itinerary",
            name="meals",
            field=models.TextField(
                blank=True, help_text="E.g., B, L & D for Breakfast, Lunch & Dinner"
            ),
        ),
    ]
