# Generated by Django 5.0.6 on 2025-04-10 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tour", "0022_alter_itinerary_meals"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndianOceanSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(default="No description available")),
                ("place", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="")),
                ("details", models.TextField(default="No details available")),
            ],
        ),
        migrations.AlterField(
            model_name="tanzania_itinerary",
            name="meals",
            field=models.TextField(
                blank=True, help_text="E.g., B, L & D for Breakfast, Lunch & Dinner"
            ),
        ),
        migrations.AlterField(
            model_name="uganda_itinerary",
            name="meals",
            field=models.TextField(
                blank=True, help_text="E.g., B, L & D for Breakfast, Lunch & Dinner"
            ),
        ),
        migrations.CreateModel(
            name="IndianOcean_Itinerary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_number", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "meals",
                    models.TextField(
                        blank=True,
                        help_text="E.g., B, L & D for Breakfast, Lunch & Dinner",
                    ),
                ),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Ind_itinerary",
                        to="tour.indianoceansite",
                    ),
                ),
            ],
            options={"ordering": ["name"],},
        ),
    ]
