# Generated by Django 5.0.6 on 2025-04-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tour", "0023_indianoceansite_alter_tanzania_itinerary_meals_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
